version: "3.3"

services:
  hapi-php:
    container_name: hapi-php
    image: nasus/hapi:80
    volumes:
      - ./../../hshop:/app
    ports: 
      - 9503:9501
    command: /bin/sh -c "cd /app && composer install && sleep 10 && php /app/bin/hyperf.php start"
  hapi-redis:
    container_name: hapi-redis
    image: redis
    volumes:
      - ./cache/redis:/data
    ports:
      - 16379:6379
  hapi-mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    volumes:
      - ./cache/mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306