version: "3.3"

services:
  hapi-develop-php:
    container_name: hapi-develop-php
    image: nasus/hapi:80
    volumes:
      - ./../../:/app
    ports: 
      - 9503:9501
    command: /bin/sh -c "echo 'hello world' > /listen.txt && tail -f /listen.txt"
  hapi-develop-node:
    container_name: hapi-develop-node
    image: node:16
    volumes:
      - ./../../:/app
    ports: 
      - 9528:9528
    command: /bin/bash -c "echo 'hello world' > /listen.txt && tail -f /listen.txt"
  hapi-develop-redis:
    container_name: hapi-develop-redis
    image: redis
    volumes:
      - ./cache/redis:/data
    ports:
      - 6379:6379
  hapi-develop-mysql:
    container_name: hapi-develop-mysql
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    volumes:
      - ./cache/mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  hapi-develop-memcached:
    container_name: hapi-develop-memcached
    image: nasus/memcached
    environment:
      USERNAME: hapi
      PASSWORD: 123456
    ports:
      - 11211:11211
  hapi-develop-rmq:
    container_name: hapi-develop-rmq
    image: rabbitmq:3.11-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
  hapi-develop-mongo:
    container_name: hapi-develop-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
  hapi-develop-elasticsearch:
    container_name: hapi-develop-elasticsearch
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  hapi-develop-kibana:
    container_name: hapi-develop-kibana
    image: kibana:7.17.17
    environment:
      ELASTICSEARCH_HOSTS: '["http://hapi-develop-elasticsearch:9200"]'
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: basic_host